Revert "Upgrade Kotlin dependencies."
This reverts commit 87df9912e32a613fb38e3fddb951969ddf16e9de.

Reverted because, otherwise, the program throws with:

Exception in thread "DefaultDispatcher-worker-1 @coroutine#110" java.lang.NoSuchMethodError: 'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism(int)'
  	at io.ktor.client.utils.CoroutineDispatcherUtilsKt.clientDispatcher(CoroutineDispatcherUtils.kt:22)
  	at io.ktor.client.engine.cio.CIOEngine$dispatcher$2.invoke(CIOEngine.kt:28)
  	at io.ktor.client.engine.cio.CIOEngine$dispatcher$2.invoke(CIOEngine.kt:27)
...

This, apparently, is because the IntelliJ platform 2022.2 bundles with kotlinx.coroutines 1.5.2 while CoroutineDispatcher.limitedParallelism(), needed by newer versions of Ktor, was introduced in 1.6.0
* https://www.jetbrains.com/legal/third-party-software/?product=IIC&version=2022.2
* https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.6.0
* https://mvnrepository.com/artifact/io.ktor/ktor-client-core/2.0.0-beta-1
* https://mvnrepository.com/artifact/io.ktor/ktor-client-core/2.0.0-rc-1